---

- name: First task
  hosts: my_servers
  connection: local
  tasks:
    - name: Create a text file with initial content
      shell: 'echo test_file_content > {{ ansible_env.HOME }}/test.txt'
      register: create_file_output

    - name: Check if the file exists and contains the correct content
      command: "cat {{ ansible_env.HOME }}/test.txt"
      register: file_content_check
      failed_when: "'test_file_content' not in file_content_check.stdout"

    - name: Change the content of the file
      shell: 'echo new_test_content > {{ ansible_env.HOME }}/test.txt'
      when: file_content_check is succeeded

    - name: Delete the test file
      file:
        path: "{{ ansible_env.HOME }}/test.txt"
        state: absent
